### ISSUE TITLE
WAR throwing Error 500 in Tomcat 8

### ISSUE THREAD

**Issue by FilBot3** [predatorian3/jruby_hello_world#1]
After building the WAR with:

```
jruby -S warble war
```

The Tomcat server would unpack the WAR, and display this in the Tomcat Console. 

```
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.21
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 23 2015 14:11:21 UTC
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.21.0
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Windows 7
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            6.1
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             C:\Program Files\Java\jre1.8.0_66
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_66-b1820-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor: Oracle Corporation
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         C:\apache\tomcat-8.0.21
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         C:\apache\tomcat-8.0.21
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=C:\apache\tomcat-8.0.21\conf\logging.properties
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=1099
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=C:\apache\tomcat-8.0.21\endorsed
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=C:\apache\tomcat-8.0.21
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=C:\apache\tomcat-8.0.21
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=C:\apache\tomcat-8.0.21\temp
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library 1.1.33 using APR version 1.5.1.
20-Jan-2016 08:34:46.519 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
20-Jan-2016 08:34:47.351 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized(OpenSSL 1.0.1m 19 Mar 2015)
20-Jan-2016 08:34:47.431 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8080"]
20-Jan-2016 08:34:47.431 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-apr-8009"]
20-Jan-2016 08:34:47.441 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1126 ms
20-Jan-2016 08:34:47.471 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
20-Jan-2016 08:34:47.471 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.21
20-Jan-2016 08:34:47.541 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive C:\apache\tomcat-8.0.21\webapps\jruby_hello_world.war
20-Jan-2016 08:34:50.952 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
io/console not supported; tty will not be manipulated
20-Jan-2016 08:34:55.235 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive C:\apache\tomcat-8.0.21\webapps\jruby_hello_world.war has finished in 7,694 ms
20-Jan-2016 08:34:55.245 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive C:\apache\tomcat-8.0.21\webapps\myapp-0.1-dev.war
20-Jan-2016 08:34:56.625 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Jan-2016 08:34:56.635 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive C:\apache\tomcat-8.0.21\webapps\myapp-0.1-dev.war has finished in 1,390 ms
20-Jan-2016 08:34:56.645 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\docs
20-Jan-2016 08:34:57.900 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Jan-2016 08:34:57.910 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\docs has finished in 1,265 ms
20-Jan-2016 08:34:57.920 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\examples
20-Jan-2016 08:34:59.614 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Jan-2016 08:34:59.674 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\examples has finished in 1,754 ms
20-Jan-2016 08:34:59.684 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\host-manager
20-Jan-2016 08:35:01.014 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Jan-2016 08:35:01.024 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\host-manager has finished in 1,340 ms
20-Jan-2016 08:35:01.024 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\manager
20-Jan-2016 08:35:02.224 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Jan-2016 08:35:02.244 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\manager has finished in 1,220 ms
20-Jan-2016 08:35:02.244 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\ROOT
20-Jan-2016 08:35:03.464 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Jan-2016 08:35:03.484 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\ROOT has finished in 1,240 ms
20-Jan-2016 08:35:03.494 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-apr-8080"]
20-Jan-2016 08:35:03.544 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-apr-8009"]
20-Jan-2016 08:35:03.544 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 16105 ms
io/console not supported; tty will not be manipulated
```

Then when the web page is loaded using `http://localhost:8080/jruby_hello_world` the following error is presented: 

```

Internal Server Error (500)
Request Method:     GET
Request URL:    http://localhost:8080/jruby_hello_world/

no such file to load -- jruby_hello_world/version from org/jruby/RubyKernel.java:1040:in 
  `require' from /C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/lib/jruby-stdlib-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in 
  `require' from C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/lib/jruby_hello_world.rb:1:in 
  `(root)' from org/jruby/RubyKernel.java:1040:in 
  `require' from /C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/lib/jruby-stdlib-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in 
  `(root)' from /C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/lib/jruby-stdlib-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in 
  `require' from org/jruby/RubyBasicObject.java:1594:in `instance_eval' from C:\apache\tomcat-8.0.21\webapps\jruby_hello_world\WEB-INF\config.ru:5:in 
  `(root)' from C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in 
  `initialize'

You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.
```

**Comment by FilBot3** [comment]
After commenting out `require 'jruby_hello_world/version'` from jruby_hello_world.rb, and rebuilding the WAR, I now get this output. 

```
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.21
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 23 2015 14:11:21 UTC
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.21.0
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Windows 7
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            6.1
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             C:\Program Files\Java\jre1.8.0_66
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_66-b18
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         C:\apache\tomcat-8.0.21
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         C:\apache\tomcat-8.0.21
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=C:\apache\tomcat-8.0.21\conf\logging.properties
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=1099
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=C:\apache\tomcat-8.0.21\endorsed
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=C:\apache\tomcat-8.0.21
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=C:\apache\tomcat-8.0.21
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=C:\apache\tomcat-8.0.21\temp
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library 1.1.33 using APR version 1.5.1.
20-Jan-2016 09:01:30.721 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
20-Jan-2016 09:01:31.671 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized (OpenSSL 1.0.1m 19 Mar 2015)
20-Jan-2016 09:01:31.761 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8080"]
20-Jan-2016 09:01:31.771 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-apr-8009"]
20-Jan-2016 09:01:31.771 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1274 ms
20-Jan-2016 09:01:31.801 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
20-Jan-2016 09:01:31.811 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.21
20-Jan-2016 09:01:31.841 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive C:\apache\tomcat-8.0.21\webapps\jruby_hello_world.war
20-Jan-2016 09:01:34.957 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
io/console not supported; tty will not be manipulated
20-Jan-2016 09:01:39.663 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive C:\apache\tomcat-8.0.21\webapps\jruby_hello_world.war has finished in 7,822 ms
20-Jan-2016 09:01:39.663 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive C:\apache\tomcat-8.0.21\webapps\myapp-0.1-dev.war
20-Jan-2016 09:01:39.693 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive C:\apache\tomcat-8.0.21\webapps\myapp-0.1-dev.war has finished in 30 ms
20-Jan-2016 09:01:39.693 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\docs
20-Jan-2016 09:01:39.723 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\docs has finished in 20 ms
20-Jan-2016 09:01:39.723 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\examples
20-Jan-2016 09:01:40.023 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\examples has finished in 300 ms
20-Jan-2016 09:01:40.023 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\host-manager
20-Jan-2016 09:01:40.053 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\host-manager has finished in 30 ms
20-Jan-2016 09:01:40.053 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\manager
20-Jan-2016 09:01:40.083 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\manager has finished in 30 ms 20-Jan-2016 09:01:40.083 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\apache\tomcat-8.0.21\webapps\ROOT
20-Jan-2016 09:01:40.113 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\apache\tomcat-8.0.21\webapps\ROOT has finished in 30 ms
20-Jan-2016 09:01:40.123 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-apr-8080"]
20-Jan-2016 09:01:40.133 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-apr-8009"]
20-Jan-2016 09:01:40.133 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 8359 ms
io/console not supported; tty will not be manipulated
```

and the webpage now displays a different error. 

```

Internal Server Error (500)
Request Method:     GET
Request URL:    http://localhost:8080/jruby_hello_world/

Server handler (trinidad,puma,reel,HTTP,webrick) not found. from C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1781:in `detect_rack_handler' 
from C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1437:in `run!' 
from C:\apache\tomcat-8.0.21\webapps\jruby_hello_world\WEB-INF\config.ru:7:in `(root)' 
from org/jruby/RubyBasicObject.java:1594:in `instance_eval' 
from C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize' 
from C:\apache\tomcat-8.0.21\webapps\jruby_hello_world\WEB-INF\config.ru:1:in `(root)'

You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.
```

**Comment by kares** [comment]
> After commenting out require 'jruby_hello_world/version' from jruby_hello_world.rb

your app is the mixture of config.ru rackup app and gem. that's why it seems as a messy .war and you need to mangle with setting default executables. if you remove .gemspec and declare dependencies in _Gemfile_ (e.g. `gem 'sinatra'` instead of `gemspec` than `bundle install`) the `warble` generated .war should detect _config.ru_ (and not built a self-executable .jar instead).

you're also mixing up bundler's gems with gems configured to be included via _warble.rb_ you should not use the two - either use Bundler or declare gems needed to be included with `config.gems +=  ...`

second by the time you're hitting `require 'jruby_hello_world/version'` (which is coming from _config.ru_ 's `require './lib/jruby_hello_world'`) **lib** is not on the `LOAD_PATH` which is clear if you look at tomcat's logs: 

```
--- $LOAD_PATH:
/opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF
/opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/gems/gems/rack-1.5.5/lib
file:/opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/lib/jruby-stdlib-1.7.24.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby
file:/opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/lib/jruby-stdlib-1.7.24.jar!/META-INF/jruby.home/lib/ruby/shared
file:/opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/lib/jruby-stdlib-1.7.24.jar!/META-INF/jruby.home/lib/ruby/1.9

22-Jan-2016 06:58:51.954 SEVERE [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log ERROR: initialization failed
 org.jruby.rack.RackInitializationException: no such file to load -- jruby_hello_world/version
    from org/jruby/RubyKernel.java:1040:in `require'
    from /opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/lib/jruby-stdlib-1.7.24.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/lib/jruby_hello_world.rb:1:in `(root)'
    from org/jruby/RubyKernel.java:1040:in `require'
    from /opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/lib/jruby-stdlib-1.7.24.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
    from /opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/lib/jruby-stdlib-1.7.24.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
    from org/jruby/RubyBasicObject.java:1594:in `instance_eval'
    from /opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/config.ru:5:in `(root)'
    from /opt/server/tomcat-8.0.30/webapps/sinatra/WEB-INF/gems/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
```

you either add it or use absolute paths for files under `lib`

**Comment by FilBot3** [comment]
If I wanted to keep the `gemspec`, then would I just use the command:

```
jruby -S bundle exec warble war
```

to build the WAR, or is my only option to remove the `gemspec` and fill in the `Gemfile`?

**Comment by FilBot3** [comment]
Adding the following to the `config.ru` in the gem's base directory allowed the WAR to be built, and ran in Tomcat

```
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
```
