### ISSUE TITLE
Warbler's executable WAR throwing Error 500

### ISSUE THREAD

**Issue by FilBot3** [predatorian3/jruby_hello_world#2]
After building the WAR as an executable to test outside of Tomcat, the following errors were thrown. 

```
C:\Users\user01\Desktop\jruby_hello_world (master){hg}
λ jruby -S bundle install
Resolving dependencies...
Using rake 10.5.0
Using bundler 1.11.2
Using rack 1.5.5 (was 1.6.4)
Using tilt 2.0.2
Using minitest 5.8.3
Using rack-protection 1.5.3
Using sinatra 1.4.6
Using jruby_hello_world 0.1.0 from source at `.`
C:/Users/user01/Desktop/jruby_hello_world/exe/jruby_hello_world maybe `gem pristine jruby_hello_world` will fix it?
Bundle complete! 4 Gemfile dependencies, 8 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

C:\Users\user01\Desktop\jruby_hello_world (master){hg}
λ jruby -S warble executable war
Downloading jetty-runner-9.2.9.v20150224.jar
rm -f jruby_hello_world.war
Creating jruby_hello_world.war

C:\Users\user01\Desktop\jruby_hello_world (master){hg}
λ java -jar jruby_hello_world.war
2016-01-20 14:37:39.764:INFO::main: Logging initialized @322ms
2016-01-20 14:37:39.771:INFO:oejr.Runner:main: Runner
2016-01-20 14:37:39.870:INFO:oejs.Server:main: jetty-9.2.9.v20150224
2016-01-20 14:37:47.576:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty
2016-01-20 14:37:47.958:INFO:/:main: INFO: jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_71-b14 +jit [Windows 7-amd64]
2016-01-20 14:37:47.959:INFO:/:main: INFO: using a shared (threadsafe!) runtime
io/console not supported; tty will not be manipulated
2016-01-20 14:37:50.371:INFO:/:main: An exception happened during JRuby-Rack startup|Server handler (trinidad,puma,reel,HTTP,webrick) not found.|--- System|jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_71-b14 +jit [Windows 7-amd64]|Time: 2016-01-20 14:37:50 -0600|Server: jetty/9.2.9.v20150224|jruby.home: file:/C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.23.jar!/META-INF/jruby.home||--- Context Init Parameters:|public.root = /|rack.env = production||--- Backtrace|RuntimeError: Server handler (trinidad,puma,reel,HTTP,webrick) not found.|  detect_rack_handler at C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1781|
          run! at C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1437|               (root) at C:\Windows\Temp\jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir\webapp\WEB-INF\config.ru:7|        instance_eval at org/jruby/RubyBasicObject.java:1594|           initialize at C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems/gems/rack-1.5.5/lib/rack/builder.rb:55|               (root) at C:\Windows\Temp\jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir\webapp\WEB-INF\config.ru:1||--- RubyGems|Gem.dir: C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems|Gem.path:|C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems|Activated gems:|  rack-1.5.5|  tilt-2.0.2|  rack-protection-1.5.3|  sinatra-1.4.6||--- Bundler|undefined method `bundle_path' for Bundler:Module||--- JRuby-Rack Config|compat_version = |default_logger = org.jruby.rack.logging.StandardOutLogger@6e7b52bf|equals = <error: 0>|err = java.io.PrintStream@61d3adb7|filter_adds_html = true|filter_verifies_resource = false|ignore_environment = false|initial_memory_buffer_size = |initial_runtimes = |jms_connection_factory = |jms_jndi_properties = |logger = org.jruby.rack.logging.ServletContextLogger@3ce15725|logger_class_name = servlet_context|logger_name = jruby.rack|maximum_memory_buffer_size = |maximum_runtimes = |num_initializer_threads = |out = java.io.PrintStream@5b031819|rackup = |rackup_path = |rewindable = true|runtime_arguments = |runtime_environment = |runtime_timeout_seconds = |serial_initialization = false|servlet_context = ServletContext@o.e.j.w.WebAppContext@39ccc8a1{/,file:/C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/,STARTING}{file:/C:/Users/user01/Desktop/jruby_hello_world/jruby_hello_world.war}|throw_init_exception = false|
2016-01-20 14:37:50.374:WARN:/:main: ERROR: initialization failed
org.jruby.rack.RackInitializationException: Server handler (trinidad,puma,reel,HTTP,webrick) not found.|?from C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1781:in `detect_rack_handler'|?from C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1437:in `run!'|?from C:\Windows\Temp\jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir\webapp\WEB-INF\config.ru:7:in `(root)'|?from org/jruby/RubyBasicObject.java:1594:in `instance_eval'|?from C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'|?from C:\Windows\Temp\jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir\webapp\WEB-INF\config.ru:1:in `(root)'|
        at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
        at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
        at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.runner.Runner.run(Runner.java:509)
        at org.eclipse.jetty.runner.Runner.main(Runner.java:557)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at WarMain.launchWebServer(WarMain.java:181)
        at WarMain.start(WarMain.java:355)
        at JarMain.doStart(JarMain.java:228)
        at WarMain.main(WarMain.java:378)
Caused by:
org.jruby.exceptions.RaiseException: (RuntimeError) Server handler (trinidad,puma,reel,HTTP,webrick) not found.
        at RUBY.detect_rack_handler(C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1781)
        at RUBY.run!(C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1437)
        at RUBY.(root)(C:\Windows\Temp\jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir\webapp\WEB-INF\config.ru:7)
        at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1594)
        at RUBY.initialize(C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/WEB-INF/gems/gems/rack-1.5.5/lib/rack/builder.rb:55)
        at RUBY.(root)(C:\Windows\Temp\jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir\webapp\WEB-INF\config.ru:1)
2016-01-20 14:37:50.401:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@39ccc8a1{/,file:/C:/Windows/Temp/jetty-0.0.0.0-8080-jruby_hello_world.war-_-any-2599163864637092233.dir/webapp/,AVAILABLE}{file:/C:/Users/user01/Desktop/jruby_hello_world/jruby_hello_world.war}
2016-01-20 14:37:50.402:WARN:oejsh.RequestLogHandler:main: !RequestLog
2016-01-20 14:37:50.435:INFO:oejs.ServerConnector:main: Started ServerConnector@51c84a4e{HTTP/1.1}{0.0.0.0:8080}
2016-01-20 14:37:50.436:INFO:oejs.Server:main: Started @10996ms
2016-01-20 14:38:41.773:INFO:/:qtp2024713894-13: DEBUG: due a previous initialization failure application instance can not be returned
2016-01-20 14:38:41.773:INFO:/:qtp2024713894-13: DEBUG: resetting rack response due exception
io/console not supported; tty will not be manipulated
2016-01-20 14:38:52.265:INFO:/:qtp2024713894-13: DEBUG: due a previous initialization failure application instance can not be returned
2016-01-20 14:38:52.266:INFO:/:qtp2024713894-13: DEBUG: resetting rack response due exception
```

**Comment by FilBot3** [comment]
After adding the load path statements to the config.ru file, the WAR now runs without issue. 

```
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
```
